import { describe, it, expect, afterAll } from 'vitest';
import { postJson, getJson, deleteFileByUrl } from '../helpers/api';

/**
 * Integration tests for File Management (Upload, List, Delete).
 *
 * Note: Upload requires multipart with a real file.
 * These tests focus on List and Delete since we can use URLs
 * generated by other operations.
 */

describe('fileManagement', () => {
	describe('listFiles', () => {
		it('should list files for the API key', async () => {
			const { status, data } = await getJson('/v1/file/list?limit=5');
			expect(status).toBe(200);
			expect(data.success).toBe(true);
			expect(typeof data.count).toBe('number');
			expect(Array.isArray(data.files)).toBe(true);
		});

		it('should respect limit parameter', async () => {
			const { status, data } = await getJson('/v1/file/list?limit=1');
			expect(status).toBe(200);
			expect(data.success).toBe(true);
			expect((data.files as unknown[]).length).toBeLessThanOrEqual(1);
		});
	});

	describe('deleteFile', () => {
		it('should create a file via generatePdf then delete it', async () => {
			// Step 1: Generate a PDF to get a URL
			const genRes = await postJson('/v1/generatePdf', {
				html_content: '<h1>Delete Test</h1>',
				output_format: 'url',
			});
			expect(genRes.status).toBe(200);
			const pdfUrl = genRes.data.pdf_url as string;
			expect(pdfUrl).toBeTruthy();

			// Step 2: Delete it
			const { status, data } = await postJson('/v1/file/delete', {
				url: pdfUrl,
			});
			expect(status).toBe(200);
			expect(data.success).toBe(true);
			expect(data.deleted).toBe(true);
		});

		it('should return error for missing URL', async () => {
			const { status, data } = await postJson('/v1/file/delete', {});
			expect(status).toBeGreaterThanOrEqual(400);
			expect(data.error).toBeTruthy();
		});

		it('should return error for non-existent file', async () => {
			const { status, data } = await postJson('/v1/file/delete', {
				url: 'https://cdn.pdfapihub.com/pdf/nonexistent_file_12345.pdf',
			});
			expect(status).toBeGreaterThanOrEqual(400);
			expect(data.error).toBeTruthy();
		});
	});
});
